### ISSUE TITLE
Null Reference Exception

### ISSUE THREAD

**Issue by Findarato** [johnkiddjr/PlexMatch-File-Generator#24] opened 2022-04-19 17:14 UTC
Tried to run your tool on the plex server and kept getting the following error

```
[12:13:51 INF] Logger attached. Startup complete. Running file generator...
[12:13:51 ERR] An unhandeled exception occurred details below:
[12:13:51 ERR] Exception Type: System.NullReferenceException
[12:13:51 ERR] Exception Message: Object reference not set to an instance of an object.
[12:13:51 ERR] Exception Source: PlexMatchGenerator
[12:13:51 ERR] Exception Stack Trace:    at PlexMatchGenerator.Services.GeneratorService.Run(GeneratorOptions options)
```

**Comment by johnkiddjr** [comment] 2022-04-19 18:00
Can you share the parameters you used?

**Comment by techie2000** [comment] 2022-04-19 19:45
I have just tried using this for the first time and observed the exact same INF/ERR msgs.

My cli input was `./PlexMatchGenerator-Linux-x64 -u http://192.168.1.115:32400 -t mysecrettoken -l /tmp/plexmatch/`

I was running 0.4.2-beta on linux (Slackware 14.2)

**Comment by johnkiddjr** [comment] 2022-04-19 20:12
This issue should be fixed with v0.4.3-beta (which is building now)

**Closed by johnkiddjr** 2022-04-19 20:12 UTC

**Comment by techie2000** [comment] 2022-04-20 07:07
> This issue should be fixed with v0.4.3-beta (which is building now)

The error is not observed in 0.4.3-beta, but when executed now returns a different error for every folder (be it tvshow, film, music etc, e.g.

`07:56:44 ERR] Missing or Invalid Folder: /webshows/linustechtips [youtube-UCXuqSBlHAE6Xw-yeJA0Tunw]`

**Comment by johnkiddjr** [comment] 2022-04-20 17:18
@techie2000 Does that folder exist on the machine running the application? If not, you'll have to use root path remapping (the -r command line switch) to change it to the path as it exists on the machine running the application

**Comment by techie2000** [comment] 2022-04-21 21:28
> @techie2000 Does that folder exist on the machine running the application? If not, you'll have to use root path remapping (the -r command line switch) to change it to the path as it exists on the machine running the application

ah, I see (I did wonder what that switch was intended for/what use-case to employ it on).
So my command would run ok if I executed it inside the plex docker container. The container maps `/webshows` to 
`/mnt/user/webshows/share/` on the host so I now execute with `-r /mnt/user/webshows/share:/webshows` and all is well in the world. I'll try repeating for all the other mappings but expect it to work now. 

Many thanks for the help 👍 

The way I read the official Plex documentation (https://support.plex.tv/articles/plexmatch/), .plexmatch only works on tvshows? If that's the case, I would have thought the code would/should only work on tvshow libraries, at least by default, and perhaps an optional flag to work on other/all other library types? 

Thanks.

**Comment by Findarato** [comment] 2022-04-25 18:18
Adding a thanks for making this work, but now I have a new Null pointer

```bash
joe@v-plex:~$ ./PlexMatchGenerator-Linux-x64 -u http://v-plex.telaranrhiod.space:32400 -t <MY CODE>
Unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PlexMatchGenerator.Helpers.ArgumentHelper.ProcessCommandLineResults(String plexToken, String plexUrl, List`1 rootPaths, String logPath)
   at PlexMatchGenerator.Helpers.CommandHelper.<>c__DisplayClass0_0.<<GenerateRootCommandAndExecuteHandler>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass18_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass20_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__19_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__6_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass9_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

I am once again running this from the plex host.

```Welcome to Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-109-generic x86_64)```
